pygments: true
markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

## Friends - those that have spoken at our meetups, is an organizer or helped the community
## below :-)
members:
  - name: Kalvir Sandhu
    gravatar: kalv@kalv.co.uk
    blurb: "Organizer of VanRuby meetups, co-founder of @caliper.io. Been hacking with Ruby for over 5 years"
    twitter: kalv
    url: http://caliper.io
  - name: Godfrey Chan
    gravatar: godfreykfc@gmail.com
    blurb: "Working with @kalv on @caliper. Contributes to open-source projects and hacks on cool side projects in my free time"
    twitter: ChanCanCode
    url: http://caliper.io
  - name: Loki Meyburg
    gravatar: loki@medeo.ca
    blurb: "Building @Medeo by day. #VanRuby hacking by night. @Crossfit604 in the morning. Motto: simplify."
    twitter: LokiMeyburg
    url: https://medeo.ca
  - name: Charles Bergeron
    gravatar: hello@charlesbergeron.ca
    blurb: "Programmer, designer, musician â€“ Building @caliper. When possible, do the cycling and yogi roles."
    twitter: ChuckBergeron
    url: http://charlesbergeron.ca
  - name: Matthew Robertson
    gravatar: matthew@cloudclinic.ca
    blurb: "A Vancouver based web developer, now hacking on @Facebook"
    twitter: mattdrobertson
    url: http://matthewrobertson.org
  - name: Brent Vatne
    gravatar: brentvatne@gmail.com
    blurb: "Co-organizer of VanRuby meetups, consultant with Madriska. Currently traveling Europe/America, but will back in Vancouver soon!"
    twitter: notbrent
    url: http://www.github.com/brentvatne
  - name: Matt Smith
    gravatar: mattr.smith@gmail.com
    blurb: "Co-organizer of VanRuby meetups, co-founder of Thinkific.com, loves building and creating new things."
    twitter: symana
    url: http://www.thinkific.com
  - name: Gabe Scholz
    gravatar: scholz.gabe@gmail.com
    blurb: "Programmer at @zozi. Knowledge is power. Eat your vegetables."
    twitter: gabescholz
    url: http://www.garbl.es
